// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD84yn30PrGeFqMl06pPadmjq13sU8IZ94',
    appId: '1:1082572253045:web:cce76bb2c076a3fcf5553c',
    messagingSenderId: '1082572253045',
    projectId: 'wave-ibrah-2026',
    authDomain: 'wave-ibrah-2026.firebaseapp.com',
    storageBucket: 'wave-ibrah-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEhciee59frbNIfNyL2y4HxN2-QJTJEMY',
    appId: '1:1082572253045:android:bcaf9e0dc1939fccf5553c',
    messagingSenderId: '1082572253045',
    projectId: 'wave-ibrah-2026',
    storageBucket: 'wave-ibrah-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbL66XTmQhrH5nAali2jBlYKLVQ4eQaV8',
    appId: '1:1082572253045:ios:5527b40986816040f5553c',
    messagingSenderId: '1082572253045',
    projectId: 'wave-ibrah-2026',
    storageBucket: 'wave-ibrah-2026.firebasestorage.app',
    iosBundleId: 'com.mohamedadel.wavemed.wavemed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD84yn30PrGeFqMl06pPadmjq13sU8IZ94',
    appId: '1:1082572253045:web:3b4cd0314096fbc8f5553c',
    messagingSenderId: '1082572253045',
    projectId: 'wave-ibrah-2026',
    authDomain: 'wave-ibrah-2026.firebaseapp.com',
    storageBucket: 'wave-ibrah-2026.firebasestorage.app',
  );

}